// <auto-generated />
using System;
using FlashCardAndQuizBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlashCardAndQuizBackend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250822004529_UpdateRegisterColumn")]
    partial class UpdateRegisterColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.DifficultyLevel", b =>
                {
                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Level");

                    b.ToTable("Difficulty_Levels", (string)null);

                    b.HasData(
                        new
                        {
                            Level = 0,
                            Label = "VeryEasy"
                        },
                        new
                        {
                            Level = 1,
                            Label = "Easy"
                        },
                        new
                        {
                            Level = 2,
                            Label = "Moderate"
                        },
                        new
                        {
                            Level = 3,
                            Label = "Hard"
                        },
                        new
                        {
                            Level = 4,
                            Label = "VeryHard"
                        });
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.FlashCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LexicalUnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LexicalUnitId")
                        .IsUnique();

                    b.ToTable("Flash_Cards", (string)null);
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.FrequencyLevel", b =>
                {
                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Level");

                    b.ToTable("Frequency_Levels", (string)null);

                    b.HasData(
                        new
                        {
                            Level = 0,
                            Label = "Obsolete"
                        },
                        new
                        {
                            Level = 1,
                            Label = "Rare"
                        },
                        new
                        {
                            Level = 2,
                            Label = "Occasional"
                        },
                        new
                        {
                            Level = 3,
                            Label = "Common"
                        },
                        new
                        {
                            Level = 4,
                            Label = "VeryCommon"
                        });
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.ImportanceLevel", b =>
                {
                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Level");

                    b.ToTable("Importance_Levels", (string)null);

                    b.HasData(
                        new
                        {
                            Level = 0,
                            Label = "VeryLow"
                        },
                        new
                        {
                            Level = 1,
                            Label = "Low"
                        },
                        new
                        {
                            Level = 2,
                            Label = "Medium"
                        },
                        new
                        {
                            Level = 3,
                            Label = "High"
                        },
                        new
                        {
                            Level = 4,
                            Label = "VeryHigh"
                        });
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.LexicalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FlashCardId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FlashCardId")
                        .IsUnique();

                    b.HasIndex("Text")
                        .IsUnique();

                    b.ToTable("Lexical_Units", (string)null);
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.Meaning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DifficultyLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<int>("FrequencyLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<int>("ImportanceLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<int>("LexicalUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<byte>("RegisterLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)2);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LexicalUnitId");

                    b.ToTable("Meanings");
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.RegisterLevel", b =>
                {
                    b.Property<byte>("Level")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Level");

                    b.ToTable("Register_Levels", (string)null);

                    b.HasData(
                        new
                        {
                            Level = (byte)0,
                            Label = "Intimate"
                        },
                        new
                        {
                            Level = (byte)1,
                            Label = "Casual"
                        },
                        new
                        {
                            Level = (byte)2,
                            Label = "Consultative"
                        },
                        new
                        {
                            Level = (byte)3,
                            Label = "Formal"
                        },
                        new
                        {
                            Level = (byte)4,
                            Label = "Frozen"
                        });
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.SentenceExample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Sentence_Examples", (string)null);
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("MeaningTag1", b =>
                {
                    b.Property<int>("MeaningId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("MeaningId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("MeaningTag1");
                });

            modelBuilder.Entity("Meanings_SentenceExamples", b =>
                {
                    b.Property<int>("MeaningsId")
                        .HasColumnType("int");

                    b.Property<int>("SentenceExamplesId")
                        .HasColumnType("int");

                    b.HasKey("MeaningsId", "SentenceExamplesId");

                    b.HasIndex("SentenceExamplesId");

                    b.ToTable("Meanings_SentenceExamples");
                });

            modelBuilder.Entity("Meanings_Tags", b =>
                {
                    b.Property<int>("MeaningsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("MeaningsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("Meanings_Tags");
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.FlashCard", b =>
                {
                    b.HasOne("FlashCardAndQuizBackend.Models.LexicalUnit", "LexicalUnit")
                        .WithOne()
                        .HasForeignKey("FlashCardAndQuizBackend.Models.FlashCard", "LexicalUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LexicalUnit");
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.LexicalUnit", b =>
                {
                    b.HasOne("FlashCardAndQuizBackend.Models.FlashCard", "FlashCard")
                        .WithOne()
                        .HasForeignKey("FlashCardAndQuizBackend.Models.LexicalUnit", "FlashCardId");

                    b.Navigation("FlashCard");
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.Meaning", b =>
                {
                    b.HasOne("FlashCardAndQuizBackend.Models.LexicalUnit", "LexicalUnit")
                        .WithMany("Meanings")
                        .HasForeignKey("LexicalUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LexicalUnit");
                });

            modelBuilder.Entity("MeaningTag1", b =>
                {
                    b.HasOne("FlashCardAndQuizBackend.Models.Meaning", null)
                        .WithMany()
                        .HasForeignKey("MeaningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashCardAndQuizBackend.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Meanings_SentenceExamples", b =>
                {
                    b.HasOne("FlashCardAndQuizBackend.Models.Meaning", null)
                        .WithMany()
                        .HasForeignKey("MeaningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashCardAndQuizBackend.Models.SentenceExample", null)
                        .WithMany()
                        .HasForeignKey("SentenceExamplesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Meanings_Tags", b =>
                {
                    b.HasOne("FlashCardAndQuizBackend.Models.Meaning", null)
                        .WithMany()
                        .HasForeignKey("MeaningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashCardAndQuizBackend.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.LexicalUnit", b =>
                {
                    b.Navigation("Meanings");
                });
#pragma warning restore 612, 618
        }
    }
}
