// <auto-generated />
using FlashCardAndQuizBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlashCardAndQuizBackend.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.DifficultyLevel", b =>
                {
                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Level");

                    b.ToTable("Difficulty_Levels", (string)null);

                    b.HasData(
                        new
                        {
                            Level = 0,
                            Label = "VeryEasy"
                        },
                        new
                        {
                            Level = 1,
                            Label = "Easy"
                        },
                        new
                        {
                            Level = 2,
                            Label = "Moderate"
                        },
                        new
                        {
                            Level = 3,
                            Label = "Hard"
                        },
                        new
                        {
                            Level = 4,
                            Label = "VeryHard"
                        });
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.FrequencyLevel", b =>
                {
                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Level");

                    b.ToTable("Frequency_Levels", (string)null);

                    b.HasData(
                        new
                        {
                            Level = 0,
                            Label = "Obsolete"
                        },
                        new
                        {
                            Level = 1,
                            Label = "Rare"
                        },
                        new
                        {
                            Level = 2,
                            Label = "Occasional"
                        },
                        new
                        {
                            Level = 3,
                            Label = "Common"
                        },
                        new
                        {
                            Level = 4,
                            Label = "VeryCommon"
                        });
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.ImportanceLevel", b =>
                {
                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Level");

                    b.ToTable("Importance_Levels", (string)null);

                    b.HasData(
                        new
                        {
                            Level = 0,
                            Label = "VeryLow"
                        },
                        new
                        {
                            Level = 1,
                            Label = "Low"
                        },
                        new
                        {
                            Level = 2,
                            Label = "Medium"
                        },
                        new
                        {
                            Level = 3,
                            Label = "High"
                        },
                        new
                        {
                            Level = 4,
                            Label = "VeryHigh"
                        });
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.LexicalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Text")
                        .IsUnique();

                    b.ToTable("Lexical_Units", (string)null);
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.Meaning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DifficultyLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<int>("FrequencyLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<int>("ImportanceLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<int>("LexicalUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<byte>("RegisterLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)2);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LexicalUnitId");

                    b.HasIndex("WordId");

                    b.ToTable("Meanings");
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.RegisterLevel", b =>
                {
                    b.Property<byte>("FormalityLevel")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("FormalityLevel");

                    b.ToTable("Register_Levels", (string)null);

                    b.HasData(
                        new
                        {
                            FormalityLevel = (byte)0,
                            Label = "Intimate"
                        },
                        new
                        {
                            FormalityLevel = (byte)1,
                            Label = "Casual"
                        },
                        new
                        {
                            FormalityLevel = (byte)2,
                            Label = "Consultative"
                        },
                        new
                        {
                            FormalityLevel = (byte)3,
                            Label = "Formal"
                        },
                        new
                        {
                            FormalityLevel = (byte)4,
                            Label = "Frozen"
                        });
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.SentenceExample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LexicalUnitId")
                        .HasColumnType("int");

                    b.Property<int>("MeaningId")
                        .HasColumnType("int");

                    b.Property<int?>("MeaningId1")
                        .HasColumnType("int");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("LexicalUnitId");

                    b.HasIndex("MeaningId");

                    b.HasIndex("MeaningId1");

                    b.ToTable("Sentence_Examples", (string)null);
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MeaningId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MeaningId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MeaningTag", b =>
                {
                    b.Property<int>("MeaningId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("MeaningId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("MeaningTag");
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.Meaning", b =>
                {
                    b.HasOne("FlashCardAndQuizBackend.Models.LexicalUnit", null)
                        .WithMany()
                        .HasForeignKey("LexicalUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashCardAndQuizBackend.Models.LexicalUnit", "Word")
                        .WithMany("Meanings")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.SentenceExample", b =>
                {
                    b.HasOne("FlashCardAndQuizBackend.Models.LexicalUnit", null)
                        .WithMany()
                        .HasForeignKey("LexicalUnitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FlashCardAndQuizBackend.Models.Meaning", "Meaning")
                        .WithMany()
                        .HasForeignKey("MeaningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashCardAndQuizBackend.Models.Meaning", null)
                        .WithMany("SentenceExamples")
                        .HasForeignKey("MeaningId1");

                    b.Navigation("Meaning");
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.Tag", b =>
                {
                    b.HasOne("FlashCardAndQuizBackend.Models.Meaning", null)
                        .WithMany("Tags")
                        .HasForeignKey("MeaningId");
                });

            modelBuilder.Entity("MeaningTag", b =>
                {
                    b.HasOne("FlashCardAndQuizBackend.Models.Meaning", null)
                        .WithMany()
                        .HasForeignKey("MeaningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashCardAndQuizBackend.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.LexicalUnit", b =>
                {
                    b.Navigation("Meanings");
                });

            modelBuilder.Entity("FlashCardAndQuizBackend.Models.Meaning", b =>
                {
                    b.Navigation("SentenceExamples");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
